### ISSUE TITLE
Invalid property /selected_repository_ids/0: `5369XXXXX` is not of type `string`.

### ISSUE THREAD

**Issue by gsuess** [pulumi/pulumi-github#247]
### What happened?

Pulumi expects `selectedRepositioryIds` to be of type number on `DependabotOrganizationSecret`, but the GitHub API expects type string .

### Steps to reproduce

```ts
const secret = new github.DependabotOrganizationSecret(name, {
    secretName: name,
    plaintextValue: value,
    visibility: "selected",
    selectedRepositoryIds: [ repository.repoId ]
  })
```

### Expected Behavior

No errors

### Actual Behavior

```
https://api.github.com/orgs/<org>/dependabot/secrets/<secret name>: 422 Invalid request
Invalid property /selected_repository_ids/0: `<number>` is not of type `string`.
```

### Output of `pulumi about`

This happened on the CI, I don't have the necessary tokens locally to reproduce it.

```
Run pulumi/actions@v3
  with:
    command: up
    stack-name: <redacted>
    work-dir: ./
    comment-on-pr: false
    github-token: ***
    parallel: <redacted>
    target-dependents: false
    refresh: false
    upsert: false
    edit-pr-comment: true
    pulumi-version: ^3
    color: auto
  env:
    <redacted>
    PULUMI_ACCESS_TOKEN: ***
Configured range: ^3
Matched version: v3.40.2
Install destination is /home/runner/.pulumi
Successfully deleted pre-existing /home/runner/.pulumi/bin
``` 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
