### ISSUE TITLE
Cannot create non-organization repository

### ISSUE THREAD

**Issue by frezbo** [pulumi/pulumi-github#53]
I just started looking at pulumi, so if I have missed something please forgive.

**Environment**

- `GITHUB_TOKEN` environment variable set

*Version*
```bash
repos (aws:none)(kc:none)(git:detached)*$ pulumi version
v2.6.1
repos (aws:none)(kc:none)(git:detached)*$
```

*package.json*
```bash
{
  "dependencies": {
    "@pulumi/github": "^1.4.1"
  }
}

```

*index.ts*
```typescript
import * as github from "@pulumi/github";

const repo = new github.Repository("demo-repo", {
    description: "Generated from automated test",
    private: true,
});

```

*Pulumi.yaml*
```yaml
name: webserver
runtime: nodejs
description: Basic example of an AWS web server accessible over HTTP.
```

*Pulumi.frezbo.yaml*
```yaml
encryptionsalt: v1:egn2DNAay4k=:v1:NwbULCM7bVi74qcg:3Ufu+yg+YYifuwaB0HU5JfwBcb23TA==
config:
  github:individual: "true"

```

**pulumi up**

```bash
repos (aws:none)(kc:none)(git:detached)*$ pulumi up
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember):
Previewing update (frezbo):
     Type                        Name              Plan
     pulumi:pulumi:Stack         webserver-frezbo
 +   └─ github:index:Repository  demo-repo         create

Resources:
    + 1 to create
    1 unchanged

Do you want to perform this update? yes
Updating (frezbo):
     Type                        Name              Status                  Info
     pulumi:pulumi:Stack         webserver-frezbo  **failed**              1 error
 +   └─ github:index:Repository  demo-repo         **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (webserver-frezbo):
    error: update failed

  github:index:Repository (demo-repo):
    error: This resource requires GitHub organization to be set on the provider.

Resources:
    1 unchanged

Duration: 1s

repos (aws:none)(kc:none)(git:detached)*$
```
